# Generated by Django 5.0.3 on 2024-05-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCv', '0005_alter_skills_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('JobTitle', models.CharField(blank=True, default='', max_length=254, verbose_name='Job Title')),
                ('CompanyLocation', models.CharField(blank=True, default='', max_length=254, verbose_name='Company and Location')),
                ('StartDate', models.DateField(verbose_name='Start Date')),
                ('EndDate', models.DateField(blank=True, default=None, null=True, verbose_name='End date')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ('StartDate',),
            },
        ),
    ]
