# Generated by Django 5.0.3 on 2024-05-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCv', '0006_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-StartDate',), 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AddField(
            model_name='experience',
            name='JobDetail',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='CompanyLocation',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Company, City, Country'),
        ),
    ]
