# Generated by Django 5.0.3 on 2024-05-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCv', '0007_alter_experience_options_experience_jobdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('School', models.CharField(blank=True, default='', max_length=254, verbose_name='Job Title')),
                ('Degree', models.CharField(blank=True, default='', max_length=254, verbose_name='Degree')),
                ('Department', models.CharField(blank=True, default='', max_length=254, verbose_name='Department')),
                ('GNO', models.CharField(blank=True, default='', max_length=254, verbose_name='GNO')),
                ('StartDate', models.DateField(verbose_name='Start Date')),
                ('EndDate', models.DateField(blank=True, default=None, null=True, verbose_name='End date')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ('-StartDate',),
            },
        ),
    ]
