# Generated by Django 5.0.3 on 2024-05-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCv', '0008_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-StartDate',), 'verbose_name': 'education', 'verbose_name_plural': 'educations'},
        ),
        migrations.AlterField(
            model_name='education',
            name='School',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='School'),
        ),
    ]
