# Generated by Django 5.0.3 on 2024-05-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCv', '0009_alter_education_options_alter_education_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='CompanyLocation',
        ),
        migrations.AddField(
            model_name='experience',
            name='Company',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='experience',
            name='Location',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Location'),
        ),
    ]
